export const FETCH_REPLY_CMT_START = 'FETCH_REPLY_CMT_START'
export const FETCH_REPLY_CMT_SUCCESS = 'FETCH_REPLY_CMT_SUCCESS'
export const FETCH_REPLY_CMT_FAILURE = 'FETCH_REPLY_CMT_FAILURE'
export const FETCH_REPLY_COMMENT = 'FETCH_REPLY_COMMENT'