export const FETCH_AVATAR_START = 'FETCH_AVATAR_START'
export const FETCH_AVATAR_SUCCESS = 'FETCH_AVATAR_SUCCESS'
export const FETCH_AVATAR_FAILURE = 'FETCH_AVATAR_FAILURE'
export const FETCH_AVATAR = 'FETCH_AVATAR'
